-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           10.4.32-MariaDB - mariadb.org binary distribution
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Copiando estrutura do banco de dados para db_filmes
CREATE DATABASE IF NOT EXISTS `db_filmes` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `db_filmes`;

-- Copiando estrutura para tabela db_filmes.filmes
CREATE TABLE IF NOT EXISTS `filmes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titulo` varchar(255) NOT NULL,
  `genero` varchar(255) NOT NULL,
  `genero_2` varchar(255) NOT NULL,
  `genero_3` varchar(255) NOT NULL,
  `sinopse` text DEFAULT NULL,
  `capa` varchar(255) DEFAULT NULL,
  `trailer_url` varchar(255) DEFAULT NULL,
  `data_lancamento` date DEFAULT NULL,
  `duracao` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Copiando dados para a tabela db_filmes.filmes: ~45 rows (aproximadamente)
INSERT INTO `filmes` (`id`, `titulo`, `genero`, `genero_2`, `genero_3`, `sinopse`, `capa`, `trailer_url`, `data_lancamento`, `duracao`) VALUES
	(1, 'Capitão América: O Primeiro Vingador', 'Ação', 'Guerra', 'Aventura', 'Steve Rogers é um jovem que participa de experiências visando a criação do supersoldado americano. Quando os oficiais militares conseguem transformá-lo em uma arma humana, eles percebem que não podem arriscar a vida do jovem nas batalhas de guerra.', '67ea97a113616.jpg', 'https://www.youtube.com/watch?v=-006iHDHK34', '2011-07-29', 124),
	(2, 'Capitã Marvel', 'Ação', 'Ficção Científica', 'Aventura', 'Em Capitã Marvel, Carol Danvers (Brie Larson) é uma ex-agente da Força Aérea norte-americana, que, sem se lembrar de sua vida na Terra, é recrutada pelos Kree para fazer parte de seu exército de elite. Inimiga declarada dos Skrull, ela acaba voltando ao seu planeta de origem para impedir uma invasão dos metaformos, e assim vai acabar descobrindo a verdade sobre si, com a ajuda do agente Nick Fury (Samuel L. Jackson) e da gata Goose.', '67ea98f2c54bd.jpg', 'https://www.youtube.com/watch?v=_q3SH0dr17k', '2019-03-07', 124),
	(3, 'Homem de Ferro', 'Ação', 'Guerra', 'Aventura', 'Tony Stark é um industrial bilionário e inventor brilhante que realiza testes bélicos no exterior, mas é sequestrado por terroristas que o forçam a construir uma arma devastadora. Em vez disso, ele constrói uma armadura blindada e enfrenta seus sequestradores. Quando volta aos Estados Unidos, Stark aprimora a armadura e a utiliza para combater o crime.', '67ea9994aade9.jpg', 'https://www.youtube.com/watch?v=2bVct5-ZxCQ', '2008-04-30', 126),
	(4, 'Homem de Ferro 2', 'Ação', 'Aventura', 'Ficção Científica', 'm um mundo ciente da existência do Homem de Ferro, o inventor bilionário Tony Stark sofre pressão de todos os lados para compartilhar sua tecnologia com as forças armadas. Ele resiste para divulgar os segredos de sua inigualável armadura, com medo de que estas informações caiam nas mãos erradas. Com a bela Pepper Potts e o amigo &amp;amp;amp;quot;Rhodey&amp;amp;amp;quot; Rhodes ao seu lado, Tony precisa forjar novas alianças e confrontar um inimigo poderoso.', '67ec9b4182fbf.jpg', 'https://www.youtube.com/watch?v=xQyNgx4YSm4', '2010-04-30', 124),
	(5, 'O Incrível Hulk ', 'Ação', 'Aventura', 'Ficção Científica', 'O cientista Bruce Banner se esconde no Brasil enquanto busca desesperadamente a cura da mutação que o transforma em um monstro incontrolável. Só assim ele poderá novamente levar uma vida normal e ficar ao lado da mulher que ama. Porém, durante este processo, ele precisa lutar contra o Abominável, um novo inimigo que quer capturá-lo.', '67ea9cce277fe.jpg', 'https://www.youtube.com/watch?v=T5IylJ3yHSU', '2008-06-13', 112),
	(6, 'Thor', 'Ação', 'Aventura', 'Fantasia', 'Thor, filho de Odin, o rei dos deuses nórdicos, logo herdará o trono de Asgard de seu idoso pai. No entanto, no dia de sua coroação, Thor reage com brutalidade quando os inimigos dos deuses entram no palácio violando o tratado. Como punição, Odin manda Thor para a Terra. Enquanto seu irmão Loki conspira em Asgard, Thor, agora sem seus poderes, enfrenta sua maior ameaça.', '67eaa12e4daf1.jpg', 'https://www.youtube.com/watch?v=GI-NJq82kH8', '2011-04-29', 114),
	(7, 'Os Vingadores', 'Ação', 'Guerra', 'Aventura', 'Loki, o irmão de Thor, ganha acesso ao poder ilimitado do cubo cósmico ao roubá-lo de dentro das instalações da S.H.I.E.L.D. Nick Fury, o diretor desta agência internacional que mantém a paz, logo reúne os únicos super-heróis que serão capazes de defender a Terra de ameaças sem precedentes. Homem de Ferro, Capitão América, Hulk, Thor, Viúva Negra e Gavião Arqueiro formam o time dos sonhos de Fury, mas eles precisam aprender a colocar os egos de lado e agir como um grupo em prol da humanidade.', '67eaa255998eb.jpg', 'https://www.youtube.com/watch?v=KeNEGtsCWEk', '2012-04-27', 143),
	(8, 'Homem de Ferro 3', 'Ação', 'Ficção Científica', 'Aventura', 'Depois de um inimigo reduzir o mundo de Tony Stark a destroços, o Homem de Ferro precisa aprender a confiar em seus instintos para proteger aqueles que ama, especialmente sua namorada, e lutar contra seu maior medo: o fracasso.', '67eaa2af46dec.jpg', 'https://www.youtube.com/watch?v=igfXmU1r_mc', '2013-04-26', 130),
	(9, 'Thor: O Mundo Sombrio', 'Ação', 'Aventura', 'Fantasia', 'Thor precisa contar com a ajuda de seus companheiros e até de seu traiçoeiro irmão Loki em um plano audacioso para salvar o universo. Entretanto, os caminhos de Thor se cruzam com Jane Foster e, dessa vez, a vida dela está realmente em perigo.', '67eaa3cdf0d6a.jpg', 'https://www.youtube.com/watch?v=BmCT2nQu90A', '2013-11-08', 112),
	(10, 'Capitão América: O Soldado Invernal', 'Ação', 'Guerra', 'Aventura', 'Após os eventos catastróficos em Nova York com os Vingadores, Steve Rogers, também conhecido como Capitão América, segue tentando se ajustar ao mundo moderno. Porém, quando um colega da agência S.H.I.E.L.D. é atacado, Steve se vê preso em uma rede de intrigas que ameaça colocar o mundo em risco. Em parceria com a Viúva Negra e Falcão, seu novo aliado, o Capitão América tem que enfrentar um misterioso e inesperado inimigo, o Soldado Invernal.', '67eaa59e61ece.jpg', 'https://www.youtube.com/watch?v=CTdvZwwShqM', '2014-04-10', 136),
	(11, 'Guardiões da Galáxia', 'Ação', 'Aventura', 'Comédia', 'O aventureiro do espaço Peter Quill torna-se presa de caçadores de recompensas depois que rouba a esfera de um vilão traiçoeiro, Ronan. Para escapar do perigo, ele faz uma aliança com um grupo de quatro extraterrestres. Quando Quill descobre que a esfera roubada possui um poder capaz de mudar os rumos do universo, ele e seu grupo deverão proteger o objeto para salvar o futuro da galáxia.', '67eaa620cf247.jpg', 'https://www.youtube.com/watch?v=8VN_l57QWyQ', '2014-07-31', 122),
	(12, 'Guardiões da Galáxia Vol. 2', 'Ação', 'Aventura', 'Comédia', 'Os Guardiões da Galáxia lutam para manter sua nova família unida enquanto desvendam os mistérios sobre o verdadeiro pai de Peter Quill', '67eaa650dca2f.jpg', 'https://www.youtube.com/watch?v=6FVulnc4poc', '2017-04-27', 136),
	(13, 'Vingadores: Era de Ultron', 'Ação', 'Ficção Científica', '', 'Ao tentar proteger o planeta de ameaças, Tony Stark constrói um sistema de inteligência artificial que cuidaria da paz mundial. O projeto acaba dando errado e gera o nascimento do Ultron. Com o destino da Terra em jogo, Capitão América, Homem de Ferro, Thor, Hulk, Viúva Negra e Gavião Arqueiro terão que se unir para mais uma vez salvar a raça humana da extinção.', '67eaa6963a8f0.jpg', 'https://www.youtube.com/watch?v=lGO6FcnZ0ek', '2015-04-23', 141),
	(14, 'Homem-Formiga', 'Ação', 'Ficção Científica', 'Aventura', 'Dr. Hank Pym transforma um talentoso ladrão no herói Homem-Formiga. Ele quer impedir que seu antigo pupilo consiga replicar a fórmula da roupa que dá o poder do encolhimento, força sobre-humana e a capacidade de controlar um exército de formigas.', '67eaa6d53ad8a.jpg', 'https://www.youtube.com/watch?v=jbbJ5WoLc1I', '2015-07-16', 117),
	(15, 'Capitão América: Guerra Civil', 'Ação', 'Aventura', 'Suspense', 'Depois do ataque de Ultron, os políticos decidem controlar os Vingadores, já que suas ações afetam toda a humanidade. A decisão coloca o Capitão América em rota de colisão com o Homem de Ferro.', '67eaa7370e729.jpg', 'https://www.youtube.com/watch?v=FRLYZn5PGuA', '2016-06-28', 148),
	(16, 'Pantera Negra', 'Ação', 'Aventura', 'Ficção Científica', 'Em Pantera Negra, após a morte do rei T&#039;Chaka (John Kani), o príncipe T&#039;Challa (Chadwick Boseman) retorna a Wakanda para a cerimônia de coroação. Nela são reunidas as cinco tribos que compõem o reino, sendo que uma delas, os Jabari, não apoia o atual governo. T&#039;Challa logo recebe o apoio de Okoye (Danai Gurira), a chefe da guarda de Wakanda, da irmã Shuri (Letitia Wright), que coordena a área tecnológica do reino, e também de Nakia (Lupita Nyong&#039;o), a grande paixão do atual Pantera Negra, que não quer se tornar rainha. Juntos, eles estão à procura de Ulysses Klaue (Andy Serkis), que roubou de Wakanda um punhado de vibranium, alguns anos atrás.', '67eaa8cfc1345.jpg', 'https://www.youtube.com/watch?v=wL4a4MafSjQ', '2018-02-15', 134),
	(17, 'Homem-Aranha: De Volta ao Lar', 'Ação', 'Aventura', '', 'Em Homem-Aranha: De Volta ao Lar, depois de atuar ao lado dos Vingadores, chegou a hora de Peter Parker (Tom Holland) voltar para casa e para a sua vida, já não mais tão normal. Lutando diariamente contra pequenos crimes nas redondezas, ele pensa ter encontrado a missão de sua vida quando o terrível vilão Abutre (Michael Keaton) surge amedrontando a cidade. O problema é que a tarefa não será tão fácil como ele imaginava.', '67eaa900cabd0.jpg', 'https://www.youtube.com/watch?v=2x-2iYxgMFU', '2017-07-06', 133),
	(18, 'Doutor Estranho', 'Ação', 'Fantasia', '', 'Stephen Strange (Benedict Cumberbatch) leva uma vida bem sucedida como neurocirurgião. Sua vida muda completamente quando sofre um acidente de carro e fica com as mãos debilitadas. Devido a falhas da medicina tradicional, ele parte para um lugar inesperado em busca de cura e esperança, um misterioso enclave chamado Kamar-Taj, localizado em Katmandu. Lá descobre que o local não é apenas um centro medicinal, mas também a linha de frente contra forças malignas místicas que desejam destruir nossa realidade. Ele passa a treinar e adquire poderes mágicos, mas precisa decidir se vai voltar para sua vida comum ou defender o mundo.', '67eaa9287e054.jpg', 'https://www.youtube.com/watch?v=HSzx-zryEgM', '2016-11-03', 115),
	(19, 'Thor: Ragnarok', 'Ação', 'Fantasia', '', 'Em Thor: Ragnarok, Thor (Chris Hemsworth) está preso do outro lado do universo. Ele precisa correr contra o tempo para voltar a Asgard e impedir o Ragnarok, a destruição de seu mundo, que está nas mãos da poderosa e implacável vilã Hela (Cate Blanchett).', '67eaa9575923c.jpg', 'https://www.youtube.com/watch?v=UvNnqWLruXA', '2017-10-26', 131),
	(20, 'Homem-Formiga e a Vespa', 'Ação', 'Aventura', 'Ficção Científica', 'Após ter ajudado o Capitão América na batalha contra o Homem de Ferro na Alemanha, Scott Lang (Paul Rudd) é condenado a dois anos de prisão domiciliar, por ter quebrado o Tratado de Sokovia. Diante desta situação, ele foi obrigado a se aposentar temporariamente do posto de super-herói. Restando apenas três dias para o término deste prazo, ele tem um estranho sonho com Janet Van Dyne (Michelle Pfeiffer), que desapareceu 30 anos atrás ao entrar no mundo quântico em um ato de heroísmo. Ao procurar o dr. Hank Pym (Michael Douglas) e sua filha Hope (Evangeline Lilly) em busca de explicações, Scott é rapidamente cooptado pela dupla para que possa ajudá-los em sua nova missão: construir um túnel quântico, com o objetivo de resgatar Janet de seu limbo.', '67eaa996157c7.jpg', 'https://www.youtube.com/watch?v=0HGBv7s1Y7E', '2018-07-05', 118),
	(21, 'Vingadores: Guerra Infinita', 'Ação', 'Aventura', 'Fantasia', 'Em Vingadores: Guerra Infinita, Thanos (Josh Brolin) enfim chega à Terra, disposto a reunir as Joias do Infinito. Para enfrentá-lo, os Vingadores precisam unir forças com os Guardiões da Galáxia, ao mesmo tempo em que lidam com desavenças entre alguns de seus integrantes.', '67eaa9b749087.jpg', 'https://www.youtube.com/watch?v=htQch8jDZ4s', '2018-04-26', 156),
	(22, 'Vingadores: Ultimato', 'Ação', 'Aventura', 'Ficção Científica', 'Em Vingadores: Ultimato, após Thanos eliminar metade das criaturas vivas em Vingadores: Guerra Infinita, os heróis precisam lidar com a dor da perda de amigos e seus entes queridos. Com Tony Stark (Robert Downey Jr.) vagando perdido no espaço sem água nem comida, o Capitão América/Steve Rogers (Chris Evans) e a Viúva Negra/Natasha Romanov (Scarlett Johansson) precisam liderar a resistência contra o titã louco.', '67eaa9d390aac.jpg', 'https://www.youtube.com/watch?v=-ZPLTV9_2so', '2019-04-25', 181),
	(23, 'Shang-Chi e a Lenda dos Dez Anéis', 'Ação', 'Fantasia', '', 'Em Shang-Chi e a Lenda dos Dez Anéis, Shang-Chi (Simu Liu) é um jovem chinês que abandonou seu país e seu pai, que lhe treinou desde criança nas artes marciais para ser um assassino ao seu dispor. Seu pai porta Dez Anéis que lhe dão poderes e longevidade, vivendo por séculos. Porém ao conhecer a mãe de Shang-Chi, ele se apaixona e tenta mudar sua vida, mas ela morre anos depois de dar a luz para a irmã mais nova de Shang-Chi, voltando causar tumulto na China. Após completar 18 anos, Shang-chi foge de seu pai em uma missão que vingaria a morte de sua mãe, mas o passado segue Shang-Chi e agora seu pai está atrás do colar que poderia resgatar sua falecida mãe. Mas o que o pai de Shang-Chi não sabe é que o mal está à espreita e ele está caindo na armadilha de um antigo e poderoso mal.', '67eaa9f3c5501.jpg', 'https://www.youtube.com/watch?v=AfHiUtxrmiY', '2021-09-02', 132),
	(24, 'Eternos', 'Ação', 'Fantasia', 'Ficção Científica', 'Eternos são seres super dotados com características como imortalidade e manipulação de energia cósmica, e eles são frutos de experiências fracassadas de seu próprio criador, o Celestial Arishem, desde a criação da Terra há milhões de anos. Destinados a salvar o mundo e a raça humana dos Deviantes, seres também criados pelo Celestial, os Eternos então derrotam tais seres e seguem caminhos diferentes, esperando que seu criador volte com boas novas. Mas após séculos e milênios aguardando ele, o grupo de heróis imortais agora precisa se preparar para uma nova ameaça, e precisam lutar contra os Deviantes novamente para garantir a segurança da humanidade. Muitos conflitos internos podem surgir, entre o amor que sentem pela Terra e a necessidade de protegê-la acima de tudo, e a fé naquilo que está acima deles. Cada um deverá lutar pelo o que acredita, e defender o que for mais importante. Eternos se passa pouco tempo após os acontecimentos de Vingadores: Ultimato (2019), dentro do universo MCU, inspirado nos quadrinhos, em adaptação da Marvel Studios.', '67eaaa0dbb83a.jpg', 'https://www.youtube.com/watch?v=PJza3ZaFeAU', '2021-11-03', 157),
	(25, 'Homem-Aranha: Longe de Casa', 'Ação', 'Aventura', '', 'Em Homem-Aranha: Longe de Casa, Peter Parker (Tom Holland) está em uma viagem de duas semanas pela Europa, ao lado de seus amigos de colégio, quando é surpreendido pela visita de Nick Fury (Samuel L. Jackson). Precisando de ajuda para enfrentar monstros nomeados como Elementais, Fury o convoca para lutar ao lado de Mysterio (Jake Gyllenhaal), um novo herói que afirma ter vindo de uma Terra paralela. Além da nova ameaça, Peter precisa lidar com a lacuna deixada por Tony Stark, que deixou para si seu óculos pessoal, com acesso a um sistema de inteligência artificial associado à Stark Industries.', '67eaaa38da7d8.jpg', 'https://www.youtube.com/watch?v=tcG3Mc4XJpg', '2019-07-04', 130),
	(26, 'Homem-Aranha: Sem Volta para Casa', 'Ação', 'Aventura', 'Fantasia', 'Em Homem-Aranha: Sem Volta para Casa, Peter Parker (Tom Holland) precisará lidar com as consequências da sua identidade como o herói mais querido do mundo após ter sido revelada pela reportagem do Clarim Diário, com uma gravação feita por Mysterio (Jake Gyllenhaal) no filme anterior. Incapaz de separar sua vida normal das aventuras de ser um super-herói, além de ter sua reputação arruinada por acharem que foi ele quem matou Mysterio e pondo em risco seus entes mais queridos, Parker pede ao Doutor Estranho (Benedict Cumberbatch) para que todos esqueçam sua verdadeira identidade. Entretanto, o feitiço não sai como planejado e a situação torna-se ainda mais perigosa quando vilões de outras versões de Homem-Aranha de outro universos acabam indo para seu mundo. Agora, Peter não só deter vilões de suas outras versões e fazer com que eles voltem para seu universo original, mas também aprender que, com grandes poderes vem grandes responsabilidades.', '67eaaa7a0d913.jpg', 'https://www.youtube.com/watch?v=CyiiEJRZjSU', '2021-12-16', 148),
	(27, 'Doutor Estranho no Multiverso da Loucura', 'Ação', 'Aventura', 'Fantasia', 'Em Doutor Estranho no Multiverso da Loucura, após derrotar Dormammu e enfrentar Thanos nos eventos de Vingadores: Ultimato, o Mago Supremo, Stephen Strange (Benedict Cumberbatch), e seu parceiro Wong (Benedict Wong), continuam suas pesquisas sobre a Joia do Tempo. Mas um velho amigo que virou inimigo coloca um ponto final nos seus planos e faz com que Strange desencadeie um mal indescritível, o obrigando a enfrentar uma nova e poderosa ameaça. O longa se conecta com a série do Disney+ WandaVision e tem relação também com Loki. O longa pertence a fase 4 do MCU onde a realidade do universo pode entrar em colapso por causa do mesmo feitiço que trouxe os vilões do Teioso para o mundo dos Vingadores e o Mago Supremo precisará contar com a ajuda de Wanda (Elizabeth Olsen), que vive isolada desde os eventos de WandaVision.', '67eaaa95881c8.jpg', 'https://www.youtube.com/watch?v=X23XCFgdh2M', '2022-05-05', 126),
	(28, 'Thor: Amor e Trovão', 'Ação', 'Aventura', 'Fantasia', 'Thor: Amor e Trovão é quarta aventura solo de Thor (Chris Hemsworth), personagem da Marvel, sendo a sequência direta de Thor: Ragnarok e o 29º filme do Universo Cinematográfico Marvel. Após os acontecimentos de Ultimato, Thor ansiando por um propósito, retorna a Nova Asgard e sua aposentadoria é interrompida por um assassino galáctico conhecido como Gorr (Christian Bale), o Carniceiro de Deus, que busca a extinção dos deuses. Para combater a ameaça, Thor pede a ajuda da Rainha Valquíria (Tessa Thompson), Korg (Taika Waititi) e Jane Foster (Natalie Portman), sua ex-namorada, que - para surpresa de Thor - inexplicavelmente consegue empunhar seu martelo mágico, Mjolnir, o que imbuiu Jane com o poder de Thor. Juntos, eles embarcam em uma aventura cósmica para descobrir o mistério da vingança do God Butcher e detê-lo antes que seja tarde demais.', '67eaaabb33a37.jpeg', 'https://www.youtube.com/watch?v=1c_W_4cNLn0', '2022-07-07', 119),
	(29, 'Pantera Negra: Wakanda Para Sempre', 'Ação', 'Aventura', 'Fantasia', 'Pantera Negra: Wakanda Para Sempre é a continuação do longa Pantera Negra, da Marvel, dirigido por Ryan Coogler e produzido por Kevin Feige. No filme, o mundo de Wakanda se expande. Após a morte do ator de T&#039;Challa (Chadwick Boseman) o foco de Wakanda Para Sempre são os personagens em volta do Pantera Negra. Rainha Ramonda (Angela Bassett), Shuri (Letitia Wright), M&#039;Baku (Winston Duke), Okoye (Danai Gurira) e as Dora Milage lutam para proteger a nação fragilizada de outros países após a morte de T&#039;Challa. Enquanto o povo de Wakanda se esforça para continuar em frente neste novo capítulo, a família e amigos do falecido rei precisam se unir com a ajuda de Nakia (Lupita Nyong&#039;o), integrante dos Cães de Guerra, e Everett Ross (Martin Freeman). Em meio a isso tudo, Wakanda ainda terá que aprender a conviver com a nação debaixo d&#039;água, Talokan, e seu rei Namor (Tenoch Huerta).', '67eaaad551840.jpg', 'https://www.youtube.com/watch?v=FR9iLjOubWc', '2022-11-10', 162),
	(30, 'Homem-Formiga e a Vespa: Quantumania', 'Ação', 'Aventura', 'Ficção Científica', 'Em Homem-Formiga e a Vespa: Quantumania, quando Cassie (Kathryn Newton), filha de Scott Lang (Paul Rudd), desenvolve um dispositivo que permitiria a comunicação com o reino quântico, o experimento termina em desastre: Cassie, Scott e sua companheira e heroína, Vespa, Hope van Dyne (Evangeline Lilly) involuntariamente se encontram no reino místico. Unindo forças com os pais de Hope, Hank Pym (Michael Douglas) e Janet van Dyne (Michelle Pfeiffer), o trio trabalha um caminho de volta enquanto os atrai para o misterioso mundo do Reino Quântico, onde encontram criaturas alienígenas e uma civilização oculta. Eles também descobrem que Janet, que ficou presa aqui por 30 anos, ainda esconde deles um ou dois segredos de seu passado: porque o misterioso Kang (Jonathan Majors), que tem a habilidade de passar, também está preso no quantum, a dimensão usada para viajar no tempo e no multiverso? E o mais importante: porque ele precisa da ajuda de Scott em uma missão importante? Será que o poderoso Kang pode ser confiável?', '67eaaaef937fe.jpg', 'https://www.youtube.com/watch?v=6jIz_8tokvg', '2023-02-16', 121),
	(31, 'Guardiões da Galáxia Vol. 3', 'Ação', 'Aventura', 'Ficção Científica', 'Em Guardiões da Galáxia Vol. 3, o amado grupo de desajustados busca se estabelecer em Lugar Nenhum, mas não demora muito para que suas vidas sejam reviradas pelos ecos do passado turbulento de Rocket (Bradley Cooper). Ainda se recuperando da perda de Gamora (Zoe Saldana), após os acontecimentos de Vingadores: Guerra Infinita (2018), Peter Quill (Chris Pratt) reúne sua equipe para defender o universo e um companheiro de equipe. Mas esta missão pode significar o fim dos Guardiões como conhecemos, se ela não for bem-sucedida. Encerramento da trilogia iniciada em 2014, sendo a continuação de Guardiões da Galáxia Vol. 2 (2017).', '67eaab167eb0d.jpg', 'https://www.youtube.com/watch?v=d1yNc9skssk', '2023-05-04', 150),
	(38, 'As Marvels', 'Ação', 'Fantasia', 'Ficção Científica', 'As Marvels é um filme norte-americano que serve como sequência para Capitã Marvel, lançado em 2019 e protagonizado por Brie Larson (O Quarto de Jack, Lessons in Chemistry). No novo longa, a Capitã - também conhecida como Carol Danvers (Larson) - está de volta para mais uma missão: agora, ela precisa lidar com consequências não intencionais que a levam a carregar o fardo de um universo desestabilizado. Porém, enquanto tenta resolver o problema, Denvers vai parar acidentalmente em um buraco de minhoca anômalo, que faz com que seus poderes acabem entrelaçados aos de outras duas heroínas. Envolvidas em um misterioso fenômeno que faz com que elas troquem de lugar sem entender a causa para tal, nascem As Marvels: a superfã Kamala Khan (Iman Vellani), também conhecida como Ms. Marvel, e a sobrinha afastada de Carol, capitã Monica Rambeau (Teyonah Parris), que agora trabalha como astronauta do programa S.A.B.E.R..', '67eaad4c9ded4.png', 'https://www.youtube.com/watch?v=YxL9wTkEgSY', '2023-11-09', 105),
	(44, 'Star Wars Episódio IV: Uma Nova Esperança', 'Aventura', 'Ficção Científica', '', 'A princesa Leia é mantida refém pelas forças imperiais comandadas por Darth Vader. Luke Skywalker e o capitão Han Solo precisam libertá-la e restaurar a liberdade e a justiça na galáxia.', '67eb052839c02.jpg', 'https://www.youtube.com/watch?v=Q8b09bE1iGQ', '1977-11-18', 121),
	(45, 'Star Wars Episódio V: O Império Contra Ataca', 'Aventura', 'Ficção Científica', '', 'Em Star Wars: Episódio V, as forças imperais comandadas por Darth Vader (David Prowse/James Earl Jones) lançam um ataque contra os membros da resistência, que são obrigados a fugir. Enquanto isso, Luke Skywalker (Mark Hamill) tenta encontrar o Mestre Yoda, que poderá ensiná-lo a dominar a &quot;Força&quot; e torná-lo um cavaleiro Jedi. No entanto, Darth Vader planeja levá-lo para o Lado Negro da &quot;Força&quot;.', '67eb05e5d001e.jpg', 'https://www.youtube.com/watch?v=P8bq_zB201Y', '1980-07-21', 124),
	(46, 'Episódio VI: O Retorno de Jedi', 'Aventura', 'Ficção Científica', '', 'Em Star Wars: Episódio VI, o Imperador Palpatine (Ian McDiarmid) está supervisionando a construção de uma nova Estrela da Morte. Enquanto isso, Luke Skywalker (Mark Hamill) liberta Han Solo (Harrison Ford) e a Princesa Leia (Carrie Fisher) das mãos de Jabba, o pior bandido das galáxias. Luke só se tornará um cavaleiro Jedi quando destruir Darth Vader, que ainda pretende atraí-lo para o lado negro da &quot;Força&quot;. No entanto a luta entre os dois vai revelar um inesperado segredo.', '67eb067aa009b.jpg', 'https://www.youtube.com/watch?v=p4vIFhk621Q', '1983-10-06', 133),
	(47, 'Star Wars Episódio I: A Ameaça Fantasma', 'Aventura', 'Fantasia', 'Ficção Científica', 'Em Star Wars: Episódio I, quando a maquiavélica Federação Comercial planeja invadir o pacífico planeta Naboo, o guerreiro Jedi Qui-Gon Jinn (Liam Neeson) e seu aprendiz Obi-Wan Kenobi (Ewan McGregor) embarcam em uma aventura para tentar salvar o planeta. Viajam com eles a jovem Rainha Amidala (Natalie Portman), que é visada pela Federação pois querem forçá-la a assinar um tratado político. Eles têm de viajar para os distantes planetas Tatooine e Coruscant em uma desesperada tentativa de salvar o mundo de Darth Sidious (Ian McDiarmid), o demoníaco líder da Federação que sempre surge em imagens tridimensionais (a ameaça fantasma). Durante a viagem, Qui-Gon Jinn conhece um garoto de nove anos que deseja treiná-lo para ser tornar um Jedi, pois o menino tem todas as qualidades para isto. Mas o tempo revelará que nem sempre as coisas são o que aparentam.', '67eb0741a99dc.jpg', 'https://www.youtube.com/watch?v=CLyVLECme84', '1999-06-24', 123),
	(48, 'Star Wars Episódio II: Ataque dos Clones', 'Aventura', 'Fantasia', 'Ficção Científica', 'Em Star Wars: Episódio 2, dez anos após a tentativa frustrada de invasão do planeta Naboo, Obi-Wan Kenobi (Ewan McGregor), Anakin Skywalker (Hayden Christensen) e Padmé Amidala (Natalie Portman) estão juntos novamente. Neste período de tempo Obi-Wan passou de aprendiz a professor dos ensinamentos jedi para Anakin, sendo que ambos foram destacados para proteger a agora senadora Amidala, que tem sua vida ameaçada por facções separatistas da República, que ameaçam desencadear uma guerra civil intergalática. Com o passar do tempo surge um romance proibido entre Anakin e Amidala, pois os cavaleiros jedi não têm permissão para se apaixonarem.', '67eb080d8b326.jpg', 'https://www.youtube.com/watch?v=zcpygp8QKN8', '2002-07-01', 142),
	(49, 'Star Wars Episódio III: A Vingança dos Sith', 'Ação', 'Aventura', 'Ficção Científica', 'Em Star Wars: Episódio III, as Guerras Clônicas estão em pleno andamento e as diferenças entre o Conselho Jedi e o Chanceler Palpatine (Ian McDiarmid) aumentam cada vez mais. Anakin Skywalker (Hayden Christensen) mantém um elo de lealdade com Palpatine, ao mesmo tempo em que luta para que seu casamento com Padmé Amidala (Natalie Portman) não seja afetado por esta situação. Seduzido por promessas de poder, Anakin se aproxima cada vez mais de Darth Sidious (Ian McDiarmid) até se tornar o temível Darth Vader. Juntos eles tramam um plano para aniquilar de uma vez por todas com os cavaleiros jedi.', '67eb088fd98ba.jpg', 'https://www.youtube.com/watch?v=J1Qf8Zc7vSk', '2005-05-20', 140),
	(50, 'Star Wars Episódio VII: O Despertar da Força', 'Ação', 'Aventura', 'Ficção Científica', 'Em Star Wars: Episódio VII, décadas após a queda de Darth Vader e do Império, surge uma nova ameaça: a Primeira Ordem, uma organização sombria que busca minar o poder da República e que tem Kylo Ren (Adam Driver), o General Hux (Domhnall Gleeson) e o Líder Supremo Snoke (Andy Serkis) como principais expoentes. Eles conseguem capturar Poe Dameron (Oscar Isaac), um dos principais pilotos da Resistência, que antes de ser preso envia através do pequeno robô BB-8 o mapa de onde vive o mitológico Luke Skywalker (Mark Hamill). Ao fugir pelo deserto, BB-8 encontra a jovem Rey (Daisy Ridley), que vive sozinha catando destroços de naves antigas. Paralelamente, Poe recebe a ajuda de Finn (John Boyega), um stormtrooper que decide abandonar o posto repentinamente. Juntos, eles escapam do domínio da Primeira Ordem.', '67eb09032c97e.jpg', 'https://www.youtube.com/watch?v=4r0287tUEgk', '2015-12-17', 135),
	(51, 'Rogue One: Uma História Star Wars', 'Ação', 'Aventura', 'Ficção Científica', 'Em Rogue One: Uma História Star Wars, Jyn Erso (Felicity Jones) foi afastada de seu pai, Galen (Mads Mikkelsen), ainda criança, devido à exigência do diretor Krennic (Ben Mendelsohn) que ele trabalhasse na construção da arma mais poderosa do Império, a Estrela da Morte. Criada por Saw Gerrera (Forest Whitaker), ela teve que aprender a sobreviver por conta própria ao completar 16 anos. Já adulta, Jyn é resgatada da prisão pela Aliança Rebelde, que deseja ter acesso a uma mensagem enviada por seu pai a Gerrera. Com a promessa de liberdade ao término da missão, ela aceita trabalhar ao lado do capitão Cassian Andor (Diego Luna) e do robô K-2SO.', '67eb096242e76.jpg', 'https://www.youtube.com/watch?v=9oISQcXuki0', '2016-12-15', 134),
	(52, 'Star Wars Episódio VIII: Os Últimos Jedi', 'Ação', 'Ficção Científica', '', 'Em Star Wars: Episódio VIII, após encontrar o mítico e recluso Luke Skywalker (Mark Hamill) em uma ilha isolada, a jovem Rey (Daisy Ridley) busca entender o balanço da Força a partir dos ensinamentos do Mestre Jedi. Paralelamente, a Primeira Ordem de Kylo Ren (Adam Driver) se reorganiza para enfrentar a Resistência.', '67eb09f1bb208.jpg', 'https://www.youtube.com/watch?v=7Ieigpxyrgo', '2017-12-14', 152),
	(53, 'Han Solo: Uma História Star Wars', 'Fantasia', 'Ficção Científica', '', 'Em dificuldade financeira, o piloto Han Solo (Alden Ehrenreich) e sua namorada Qi&#039;ra (Emilia Clarke) buscam algum trabalho. Eles conseguem pôr as mãos em uma substância valiosa, mas perigosa, que acaba levando à perseguição do Império e à separação entre os dois. Preocupado, Han usa toda a sua esperteza para se infiltrar num plano arriscado, mas que pode render a oportunidade de voltar à terra natal e reencontrar a sua amada. Caso ele falhe, vai ter que prestar contas ao perigoso Dryden Vos (Paul Bettany). No caminho, o piloto encontra parceiros importantes, como Chewbacca (Joonas Suotamo) e Lando Calrissian (Donald Glover), o proprietário original da Millennium Falcon.', '67eb0a4549bb0.jpg', 'https://www.youtube.com/watch?v=UtpnRFzZWlM', '2018-05-24', 135),
	(54, 'Star Wars Episódio IX: A Ascensão Skywalker', 'Aventura', 'Ficção Científica', '', 'Em Star Wars: Episódio IX, com o retorno do Imperador Palpatine (Ian McDiarmid), todos voltam a temer seu poder. Assim, a Resistência toma a frente da batalha que ditará os rumos da galáxia. Treinando para ser uma completa Jedi, Rey (Daisy Ridley) ainda se encontra em conflito com seu passado e futuro, mas teme pelas respostas que pode conseguir a partir de sua complexa ligação com Kylo Ren (Adam Driver), que também se encontra em conflito pela Força.', '67eb0b551d7f1.jpg', 'https://www.youtube.com/watch?v=i3X-xQIjqws', '2019-12-19', 142),
	(57, 'Harry Potter e a Pedra Filosofal', 'Aventura', 'Fantasia', '', 'Harry Potter (Daniel Radcliffe) é um garoto órfão de 10 anos que vive infeliz com seus tios, os Dursley. Até que, repentinamente, ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente Harry é impedido de ler a carta por seu tio Válter (Richard Griffiths), mas logo ele recebe a visita de Hagrid (Robbie Coltrane), o guarda-caça de Hogwarts, que chega em sua casa para levá-lo até a escola. A partir de então Harry passa a conhecer um mundo mágico que jamais imaginara, vivendo as mais diversas aventuras com seus mais novos amigos, Rony Weasley (Rupert Grint) e Hermione Granger (Emma Watson).', '67ec8a75e8913.jpg', 'https://www.youtube.com/watch?v=SFzft_2dcV0', '2001-11-23', 152),
	(58, 'Harry Potter e a Câmara Secreta', 'Fantasia', '', '', 'De férias na casa de seus tios Dursley, Harry Potter (Daniel Radcliffe) recebe a inesperada visita de Dobby, um elfo doméstico, que veio avisá-lo para não retornar à Escola de Magia de Hogwarts, pois lá correrá um grande perigo. Harry não lhe dá ouvidos e decide retornar aos estudos, enfrentando um 2º ano recheado de novidades. Uma delas é a contratação do novo Professor de Defesa Contra as Artes das Trevas, Gilderoy Lockhart (Kenneth Branagh), que é considerado um grande galã e não perde uma oportunidade de fazer marketing pessoal. Porém, o aviso de Dobby se confirma e logo toda Hogwarts está envolvida em um mistério que resulta no aparecimento de alunos petrificados.', '67ec8b79e2249.jpg', 'https://www.youtube.com/watch?v=cf0rRYvDuys', '2002-11-22', 158),
	(59, 'Harry Potter e o Prisioneiro de Azkaban', 'Aventura', 'Fantasia', '', 'O 3º ano de ensino na Escola de Magia e Bruxaria de Hogwarts se aproxima. Porém um grande perigo ronda a escola: o assassino Sirius Black (Gary Oldman) fugiu da prisão de Azkaban, considerada até então como à prova de fugas. Para proteger a escola são enviados os Dementadores, estranhos seres que sugam a energia vital de quem se aproxima deles, que tanto podem defender a escola como piorar ainda mais a situação.', '67ed5a26eb4cf.jpg', 'https://www.youtube.com/watch?v=e02fwhC6DiQ', '2004-06-04', 141);

-- Copiando estrutura para tabela db_filmes.filme_genero
CREATE TABLE IF NOT EXISTS `filme_genero` (
  `filme_id` int(11) NOT NULL,
  `genero_id` int(11) NOT NULL,
  PRIMARY KEY (`filme_id`,`genero_id`),
  KEY `genero_id` (`genero_id`),
  CONSTRAINT `filme_genero_ibfk_1` FOREIGN KEY (`filme_id`) REFERENCES `filmes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `filme_genero_ibfk_2` FOREIGN KEY (`genero_id`) REFERENCES `generos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Copiando dados para a tabela db_filmes.filme_genero: ~3 rows (aproximadamente)
INSERT INTO `filme_genero` (`filme_id`, `genero_id`) VALUES
	(1, 1),
	(1, 2),
	(1, 13);

-- Copiando estrutura para tabela db_filmes.generos
CREATE TABLE IF NOT EXISTS `generos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(100) NOT NULL,
  `descricao` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Copiando dados para a tabela db_filmes.generos: ~18 rows (aproximadamente)
INSERT INTO `generos` (`id`, `nome`, `descricao`) VALUES
	(1, 'Ação', 'É um gênero de filme protagonizado por um herói de ação e que apresenta predominantemente sequências de perseguição, lutas, tiroteios, explosões e acrobacias de dublês.'),
	(2, 'Aventura', 'É um gênero cinematográfico que pode ser caracterizado como uma história onde um herói enfrenta uma série de obstáculos, exibindo coragem ao enfrentar situações que fogem ao cotidiano.'),
	(3, 'Comédia', 'É um gênero de ficção que consiste em discursos ou obras que pretendem ser humorísticos ou divertidos por induzir o riso, especialmente no teatro, cinema, comédia stand-up, televisão, rádio, livros ou qualquer outro meio de entretenimento.'),
	(6, 'Comédia Romântica', 'É um subgênero cinematográfico dos gêneros comédia e romance.'),
	(7, 'Documentário', 'É uma produção artística, via de regra um filme, não-ficcional, que se caracteriza principalmente pelo compromisso da exploração da realidade.'),
	(8, 'Drama', 'É o modo específico de ficção representado na performance: uma peça, ópera, mímica, balé, etc., realizada em um teatro, rádio ou televisão.'),
	(9, 'Espionagem', 'É um gênero de filme que trata do tema da espionagem ficcional, seja de forma realista (como as adaptações de John le Carré) ou como base para a fantasia (como muitos filmes de James Bond).'),
	(10, 'Faroeste', 'O chamado cinema western, também popularizado sob os termos "filmes de cowboys" ou "filmes de faroeste", compõe um gênero clássico do cinema norte-americano (ainda que outros países tenham produzido westerns, como aconteceu na Itália, com o seu western spaghetti).'),
	(11, 'Fantasia', 'É um gênero da ficção em que geralmente se utilizam fenômenos sobrenaturais, mágicos e outros como elementos primários do enredo, tema ou configuração.'),
	(12, 'Ficção Científica', 'É um gênero de filme que utiliza a ficção científica e a ficção especulativa com base científica de fenômenos que não são totalmente aceitos pela ciência moderna, como formas de vida extraterrestre, outros planetas, percepção extra-sensorial e viagem no tempo, juntamente com elementos futuristas tais como naves espaciais, robôs, ciborgues, rebelião das máquinas, viagens interestelares ou outras tecnologias.'),
	(13, 'Guerra', 'É um gênero cinematográfico que de um lado se confunde com filmes de ação e épicos, principalmente quando são mostrados dramas históricos, enquanto por outro tem se prestado, ao longo da história, ao uso propagandístico ou patriótico dos governos de todos os países que, em maior ou menor grau, buscam obter dividendos através de obras que retratam conflitos pontuais ou do passado.'),
	(14, 'Policial', 'É um gênero que quase sempre envolvem crimes e criminosos, policiais e detetives particulares, mafiosos e ladrões.'),
	(15, 'Mistério', 'É um gênero cinematográfico que gira em torno da solução de um problema ou de um crime.'),
	(16, 'Musical', 'É um estilo de filme, no qual a narrativa se apoia sobre uma sequência de músicas coreografadas, utilizando música, canções e coreografia como narrativa predominante ou exclusivamente.'),
	(17, 'Romance', 'Podem ser definidos como aqueles cujo enredo se desenvolve em torno de um envolvimento amoroso entre os protagonistas. Um dos pré-requisitos do gênero é de que o filme tenha um "final feliz"; contudo, alguns filmes com final triste também podem ser considerados filmes do gênero romântico.'),
	(18, 'Terror', 'É um gênero cinematográfico que procura uma reação emocional negativa dos espectadores, ao jogar com os medos primários da audiência.'),
	(19, 'Thriller', 'É um gênero da literatura, filmes, jogos eletrônicos e televisão que usa o suspense, tensão e excitação como principais elementos do gênero.');

-- Copiando estrutura para tabela db_filmes.usuarios
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `senha` varchar(255) NOT NULL,
  `permissao` enum('admin','user') DEFAULT 'user',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Copiando dados para a tabela db_filmes.usuarios: ~4 rows (aproximadamente)
INSERT INTO `usuarios` (`id`, `nome`, `email`, `senha`, `permissao`) VALUES
	(1, 'admin', 'admin@gmail.com', 'admin', 'admin'),
	(2, 'diemisson', 'diemisson.liima@gmail.com', '1234', 'user'),
	(3, 'james', 'james@gmail.com', '1234', 'user'),
	(28, 'claudio sales', 'sallesc012@gmail.com', '20010208', 'user');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
